"""Admin User, OTP and Policies

Revision ID: 38733b6d0d5c
Revises: 
Create Date: 2024-08-03 16:50:05.252304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38733b6d0d5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('otp_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_number', sa.String(length=100), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('policy_cover', sa.Integer(), nullable=False),
    sa.Column('policy_status', sa.Enum('REQUIREMENTS_AWAITED', 'REQUIREMENTS_CLOSED', 'UNDERWRITING', 'POLICY_ISSUED', 'POLICY_REJECTED', name='policystatus'), nullable=False),
    sa.Column('policy_number', sa.String(length=100), nullable=True),
    sa.Column('medical_type', sa.Enum('TELE_MEDICALS', 'PHYSICAL_MEDICALS', name='medicaltype'), nullable=True),
    sa.Column('medical_status', sa.Enum('PENDING', 'SCHEDULED', 'WAITING_FOR_REPORT', 'DONE', name='medicalstatus'), nullable=True),
    sa.Column('remarks', sa.String(length=200), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['admin_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_number'),
    sa.UniqueConstraint('policy_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policies')
    op.drop_table('otp_log')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
